/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdcc5",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#301400",
        "on-primary": "#1000a9",
        "error": "#ffb4ab",
        "secondary": "#bec6e0",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-container": "#0d0096",
        "outline-variant": "#464554",
        "surface-bright": "#393841",
        "on-surface": "#e4e1ed",
        "tertiary": "#ffb783",
        "on-surface-variant": "#c7c4d7",
        "surface-container": "#1f1f27",
        "on-secondary-container": "#adb4ce",
        "outline": "#908fa0",
        "inverse-surface": "#e4e1ed",
        "primary-container": "#8083ff",
        "on-tertiary": "#4f2500",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#07006c",
        "primary": "#c0c1ff",
        "inverse-on-surface": "#303038",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-low": "#1b1b23",
        "tertiary-fixed-dim": "#ffb783",
        "on-background": "#e4e1ed",
        "inverse-primary": "#494bd6",
        "secondary-container": "#3f465c",
        "background": "#13131b",
        "surface": "#13131b",
        "on-error": "#690005",
        "tertiary-container": "#d97721",
        "surface-dim": "#13131b",
        "surface-container-high": "#292932",
        "on-tertiary-container": "#452000",
        "on-secondary": "#283044",
        "secondary-fixed": "#dae2fd",
        "surface-variant": "#34343d",
        "surface-container-highest": "#34343d",
        "on-tertiary-fixed-variant": "#703700",
        "surface-container-lowest": "#0d0d15",
        "primary-fixed": "#e1e0ff",
        "surface-tint": "#c0c1ff",
        "on-secondary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#2f2ebe"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "40px",
        "unit": "4px",
        "lg": "24px",
        "margin": "32px",
        "sm": "8px",
        "gutter": "24px",
        "max_width": "1440px",
        "xs": "4px",
        "md": "16px"
      },
      fontFamily: {
        "h2": ["Outfit", "sans-serif"],
        "mono": ["monospace"],
        "h3": ["Outfit", "sans-serif"],
        "display": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "h1": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "mono": ["13px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "h3": ["18px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
